name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
      

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows/Static/X86/Release",
            os: windows-2019,
            config: Release,
            args: -G "Visual Studio 16 2019" -A Win32,
          }
          - {
            name: "Windows/Static/X64/Release",
            os: windows-2019,
            config: Release,
            args: -G "Visual Studio 16 2019" -A x64,
          }
          - {
            name: "Ubuntu/18.04/Static/X64/Release",
            os: ubuntu-18.04,
            config: Release,
            cmake_extra_args: "-DCMAKE_C_COMPILER=/usr/bin/gcc-10 -DCMAKE_CXX_COMPILER=/usr/bin/g++-10",
          }
          - {
            name: "MacOSX/Static/X64/Release",
            os: macos-10.15,
            config: Release,
            args: "",
          }
    steps:
      - uses: actions/checkout@v3
      
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.1
      
      - name: Create Work Dir
        run: mkdir build
      
      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        working-directory: ./build
        run: cmake .. ${{ matrix.config.cmake_extra_args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }}
    

      name: Build
        # Build your program with the given configuration
        working-directory: ./build
        run: cmake --build . -j --config ${{ matrix.config.config }}

      - name: Test
        # Execute tests defined by the CMake configuration.  
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        working-directory: ./build
        run: ctest -j -C ${{ matrix.config.config }}